title = input()
content = input()
comments = input()
print("<h1>")
print(f"    {title}")
print("</h1>")
print("<article>")
print(f"    {content}")
print("</article>")
while comments != "end of comments":
    print("<div>")
    print(f"    {comments}")
    print("</div>")
    comments = input()
